### ISSUE TITLE
Keep correct ordering of chunks when building a body value

### ISSUE THREAD

**Issue by paluh** [cprussin/purescript-httpure#117]
Hi,

It seems that there is a subtle bug in `body` buildup function where chunks are accumulated.

Current handler which processes single incoming chunk calls multiple functions internally before it appends result to the `body` value (we have `Ref.modify` and its callback, `void` and multiple calls inside `Stream.onDataString`):

https://github.com/cprussin/purescript-httpure/blob/master/src/HTTPure/Body.purs#L87

It seems that sometimes javascript event loop interrupts chunk processing (probably on one of this internal function call frames) and runs handler for the next `chunk` before appending currently processed chunk. As a result it is possible to get `body` which has correct length but is a concatenation of chunks in a wrong order. We have noticed this behavior only for large chunks and on a nodejs instance behind nginx reverse proxy...

These are related changes which seem to fix this problem:

[Body.purs](https://github.com/cprussin/purescript-httpure/compare/master...paluh:master#diff-93ef2a57382a5283cb4367600c80bc53R52)

[Body.js](https://github.com/cprussin/purescript-httpure/compare/master...paluh:master#diff-13cc2b11e9f529f10a51e0cb0afbd873R1)

I can provide clean PR if you suggest how would you like to fix this bug. I'm not sure if I able to provide any regression for it...

**Comment by cprussin** [comment]
Interesting bug!  It seems like this should be fixable without resorting to FFI no?  If there's no fix outside FFI, then I believe that the FFI portion and purescript binding should be part of [purescript-node-buffer](https://github.com/purescript-node/purescript-node-buffer) instead since it sounds like a bug caused by the binding itself.  Other than that, the way you have it fixed makes sense, the only modification I would request is that you add a comment explaining the bug and why it's coded that way since we won't likely be able to add a unit test for this case.

**Comment by cprussin** [comment]
For what it's worth, I've had it in the back of my mind to revisit this for some time.  I'd like to support streaming requests (#63) so likely we'll end up getting rid of this as being the default and expose it as a helper instead.  The fix will still need to go in the helper of course, so still worth fixing here.

**Comment by cprussin** [comment]
@paluh any chance you've been able to put more thought into this one?  If there's any reason we can't get the FFI binding in -node-buffer, I'm happy to accept a PR to put one in httpure temporarily, at least so that httpure isn't buggy.

**Comment by paluh** [comment]
Hi @cprussin ,

> any chance you've been able to put more thought into this one?

Yeah, I thought a bit about this during my offline weekend ;-)


> If there's any reason we can't get the FFI binding in -node-buffer (..)

I'm not sure if I'm able to propose any serious and reasonable API change / improvement for `-node-buffer` at the moment...


> I'm happy to accept a PR to put one in httpure temporarily, at least so that httpure isn't buggy.

I'm going to provide it today evening (around 20:00 - 22:00 09-24 CEST). Should I leave`aggregateChunk` like it is in `Body.purs` or move it to some `Utils/Node/Stream.purs`  submodule?

**Comment by cprussin** [comment]
Woot, thanks @paluh!  Much appreciated!

> I'm not sure if I'm able to propose any serious and reasonable API change / improvement for -node-buffer at the moment...

At the very least, I think we should open the discussion in the form of a issue on `-node-buffer`.  We can defer to the folks most familiar with the `-node-buffer` package to help us come up with the correct solution, but I certainly think long term this problem should be solved by that package, not this one, so we should start the discussion.  I'd just prefer you to, since I haven't seen any such bug and so I can't provide details on repro cases or theories...

**Comment by paluh** [comment]
> At the very least, I think we should open the discussion in the form of a issue on -node-buffer (...) so we should start the discussion. I'd just prefer you to, since I haven't seen any such bug and so I can't provide details on repro cases or theories...

Ok, I'm going to open an issue under `-node-buffer` and use our case from `HTTPure`.

**Comment by cprussin** [comment]
No problem, it's all open source :) I'm happy to weigh in as I can, but tbh it doesn't really make sense to me how this could be happening (node shouldn't interrupt a synchronous call stack) and I haven't been able to repro so I'm not so sure how to advist
