### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by amkhlv** [cprussin/purescript-httpure#200]
`let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.14.5-20220224/packages.dhall sha256:67cc3d4f0e8fb72bb1413ba94ddd72a3ceb0783eb725e3b22ad7568b3b581163

in  upstream
with httpure = 
  { dependencies = [
      "aff"
    , "arrays"
    , "bifunctors"
    , "console"
    , "effect"
    , "either"
    , "foldable-traversable"
    , "foreign-object"
    , "js-uri"
    , "maybe"
    , "newtype"
    , "node-buffer"
    , "node-fs"
    , "node-http"
    , "node-streams"
    , "options"
    , "ordered-collections"
    , "prelude"
    , "refs"
    , "strings"
    , "tuples"
    , "type-equality"
  ] : List Text
  , repo = "https://github.com/citizennet/purescript-httpure"
  , version = "v0.16.0"
  }
`
with 
`{ name = "my-project"
, dependencies = [ 
  "argonaut-codecs"
, "argonaut-core"
, "console"
, "effect"
, "prelude"
, "psci-support" 
, "httpure"
]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
`
build fails with these errors:
`Compiling HTTPure.Body
Compiling HTTPure.MultiHeaders
Error 1 of 2:

  in module HTTPure.Body
  at .spago/httpure/v0.16.0/src/HTTPure/Body.purs:121:5 - 121:89 (line 121, column 5 - line 121, column 89)

    Could not match type
                 
      Function t0
                 
    with type
            
      Effect
            

  while trying to match type t0 -> t1
    with type Effect Unit
  while checking that expression (apply const) ((apply done) (Right unit))
    has type Effect Unit
  in value declaration bodyString

  where t1 is an unknown type
        t0 is an unknown type

  See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
  or to contribute content related to this error.

Error 2 of 2:

  at .spago/httpure/v0.16.0/src/HTTPure/MultiHeaders.purs:1:1 - 133:112 (line 1, column 1 - line 133, column 112)

    Unable to parse foreign module:

      .spago/httpure/v0.16.0/src/HTTPure/MultiHeaders.js

      The module could not be parsed:

      ExportToken {tokenSpan = TokenPn 0 1 1, tokenLiteral = "export", tokenComment = []}

  See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingFFIModule.md for more information,
  or to contribute content related to this error.

`

**Comment by arthurxavierx** [comment]
Hey @amkhlv! It would be nice to know more details about the error. I see that you're using `https://github.com/purescript/package-sets/releases/download/psc-0.14.5-20220224/packages.dhall` for your package set. As the name of the package set says, its packages are compatible with PureScript v0.14.5, whereas purescript-httpure v0.16.0 (which is the one you're overriding), is only compatible with PureScript ≥ v0.15.0.

In order to solve the issue I believe you have two options:
1. Upgrade your compiler version and your package set.
2. Do not override purescript-httpure and use the version provided by the chosen package set, as it's guaranteed to work with the compiler version of the package set and with all other packages.
